import type { Metadata } from "next";

import "./globals.css";
import { Inter } from "next/font/google";

const interFont = Inter({
  weight: "400",
  preload: true,
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={interFont.className}>
        <main className="bg-[hsl(250,24%,9%)] flex justify-center items-center min-h-screen">{children}</main>
      </body>
    </html>
  );
}
